blank_issues_enabled: false
contact_links:
  - name: Wiki
    url: https://starcitizen-lug.github.io
    about: Installation issues, troubleshooting, and recent news/changes
  - name: Community Support
    url: https://discord.gg/QRexSTkF25
    about: Get help in our Discord tech support channel. It's bridged to our Matrix space too! (See wiki above for links)
