on:
  workflow_dispatch:
  create:
    tags:
      - 'v[0-9].[0-9]-[0-9]'

name: Release AppImage

permissions:
    contents: write

jobs:
  parse:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.fetch_lug.outputs.TAG }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Fetch latest tag
        id: fetch_lug
        run: |
          git fetch --tags
          echo "TAG=$(git describe --tags "$(git rev-list --tags --max-count=1)")" >> $GITHUB_OUTPUT
      - name: debug
        run: |
          echo "tag is ${{ steps.fetch_lug.outputs.TAG }}"
  build:
    needs: parse
    uses: mactan-sc/lug-helper-appimage/.github/workflows/build.yml@main
    with:
      tag: ${{ needs.parse.outputs.TAG }}
  release:
    runs-on: ubuntu-latest
    needs: [parse, build]
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          name: lug helper ${{ needs.parse.outputs.TAG }}
          files: LUG-Helper-${{ needs.parse.outputs.TAG }}.AppImage
          tag_name: ${{ needs.parse.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
